For Windows OS, revert the usage of cmd.exe by default (new option)
codehaus-plexus/plexus-utils pull request #110
Opened 2020-12-21 11:29 UTC by axel3rd

This PR is an update of old previous staling PR #42

----

cf. #17 (comments from May 2018): Revert the usage of `cmd.exe` by default (on Windows), because prevents the destroy/kill launched by this way when `CTRL+C`.

Allow this behavior by the usage of a new method:
```
Commandline cmd = new Commandline();
cmd.setForceShellOsSpefic( true );
```
----
This PR should be chosen or #109.

2020-12-21 12:02 UTC, michael-o requested changes

2020-12-21 12:02 UTC, michael-o commented on src/main/java/org/codehaus/plexus/util/cli/Commandline.java
> +    private boolean forceShellOsSpefic;
There is a typo in the variable name

2020-12-21 13:35 UTC, axel3rd commented
*Note: GitHub action verify problem with Java 16-ea is not part of this PR.*

2021-01-04 11:52 UTC, axel3rd commented
(@michael-o: Requested changes have been done)

2021-01-04 13:13 UTC, axel3rd commented
> Note: GitHub action verify problem with Java 16-ea is not part of this PR.

See #116

2021-02-26 19:26 UTC, axel3rd commented
Is this PR (or #109) not relevant 😢 ?

2021-02-26 20:36 UTC, michael-o commented
I will try to pick this up next month.

2021-02-26 22:46 UTC, axel3rd commented
Thank you !

2021-07-28 16:11 UTC, axel3rd commented
> I will try to pick this up next month.

😁 (#FriendlyBump)

2021-07-29 07:35 UTC, michael-o commented
Thanks for the note. I think both Bourne Shell and Cmd Shell must go. There is no use for that.

2021-07-29 08:13 UTC, axel3rd commented
> I think both Bourne Shell and Cmd Shell must go. There is no use for that

=> We abandon this PR, and perhaps #109 depending the relevance ?

2021-07-29 08:26 UTC, michael-o commented
I first need to understand why this was done at all. Maybe lack of knowledge. Currently, I don't see a reason why we should wrap these command into a shell execution at all.

2021-07-29 17:09 UTC, rfscholte commented
From what I've always understood only with a new shell you can isolate system properties and environment variables.

2021-07-29 17:24 UTC, michael-o commented
System properties are pure args to a process. There is no connection to the parent process. If want to isolate env vars, you can do that easily with the ProcessBuilder. It works just fine. Moreover, you cannot start with a nude environment because some processes expect default env vars and they won't be present. Just set those you need and that's it.

2026-08-16 20:34 UTC, slachiewicz commented
@axel3rd this and #109 are alternatives, and carrying both means the choice gets re-litigated every time someone triages the repo. Sorry it has sat this long.

#109 looks like the one to keep, and you said as much yourself in https://github.com/codehaus-plexus/plexus-utils/pull/110#issuecomment-888902458 after michael-o's "both Bourne Shell and Cmd Shell must go". `setForceShellOsSpecific` adds public API that keeps `CmdShell` in the surface, so it would need deprecating again under that direction; #109 changes the same Windows default without new API and in a third of the diff.

That is not a merge decision for #109 either. It conflicts with master and predates the Spotless and JUnit 5 migrations, so it needs work before it can land, and the change of default deserves its own release note whenever it does.

Would you be willing to close this one in favour of #109?

*This comment was created with AI assistance.*

2026-08-16 20:59 UTC, axel3rd commented
> Would you be willing to close this one in favour of https://github.com/codehaus-plexus/plexus-utils/pull/109?

👋 @slachiewicz, agree with that 👌

2026-08-16 20:59 UTC, closed without merging