Use more Java 8, NIO
codehaus-plexus/plexus-utils pull request #201
Opened 2022-04-23 20:38 UTC by slachiewicz

in general, looks many methods that use File can be potentially deprecated with a suggestion to use NIO. Sometime ago Elharo made that type of cleanup for maven-shared-utils 

I'm not sure how performant will be switched from Reader/Stream to Files.read + new String

2022-04-23 20:41 UTC, michael-o requested changes
I would rather deprecate everything which is a one or two liner with NIO2.

2022-04-26 06:30 UTC, gnodet requested changes

2022-04-26 06:30 UTC, gnodet commented on src/main/java/org/codehaus/plexus/util/FileUtils.java
> +        return String.join( ",", DirectoryScanner.DEFAULTEXCLUDES);
Missing space before the `)`

2022-04-26 06:30 UTC, gnodet commented on src/main/java/org/codehaus/plexus/util/NioFiles.java
> +@Deprecated
Provide a pointer to a replacement.  Simply indicating, `replace with direct NIO calls` would be fine, but it's always a pain when you run into a deprecated method and you need to go through the GitHub history to understand why it has been deprecated and what to use instead.

2022-06-09 21:25 UTC, closed without merging